name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get install -y libgtest-dev libcurl4-openssl-dev

      - name: Check format
        run: clang-format -n -Werror src/**/*.cc src/**/*.h tests/**/*.cc

      - name: Configure build
        run: |
          cmake -Bbuild -S . -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Run tests
        env:
          AOC_SESSION_TOKEN: ${{secrets.AOC_SESSION_TOKEN}}
          CTEST_OUTPUT_ON_FAILURE: 1
        run: cd build/tests/days && ctest
